export enum OrderStatusListEnum {
    OutSource = 0,
    Submitted = 1,
    Reviewed = 2,
    Pending = 3,
    Assigned = 4,
    Scheduled = 5,
    TripStarted = 6,
    AtPickUp = 7,
    Loading = 8,
    AttemptPickUp = 9,
    PickedUp = 10,
    InTransit = 11,
    AttemptDelivery = 12,
    AtDropOff = 13,
    Unloading = 14,
    Completed = 15,
    Delivered = 16,
    Cancelled = 17,
}
